### ISSUE TITLE
Hash 'word' order in reverse order compared to ThreatExchange/pdq/ (local order of each 16 bit section is correct) 

### ISSUE THREAD

**Issue by BarrettOlson** [faustomorales/pdqhash-python#1]
This could create issues for those trying to compare hashes that use a different pdq implementations.

Test used to validate output are in reverse order (local order of each 16 bit section is correct) 
https://github.com/facebook/ThreatExchange/issues/319

This results in hashes like the following:
Expected: 
e8ecb3355e3125c8e2ce3f30a0d4e84f8682b878b3c34cdbdb063278db27d992
Output:
d992db273278db064cdbb3c3b8788682e84fa0d43f30e2ce25c85e31b335e8ec

Hotfix that should work for users of the lib (still investigating):
```
hash_vector, quality = pdqhash.compute(image)
hash_vector = np.array(hash_vector).reshape(16, 16)[::-1, :].flatten()
```

**Comment by faustomorales** [comment]
Ah, interesting. Thank you for sharing here. It seems as though we can fix this by simply removing the reshape we currently apply in the library (see the tail end of the line below).

https://github.com/faustomorales/pdqhash-python/blob/3c35e8dd2842c98055231aad2c60d835d0628b68/pdqhash/bindings.pyx#L64

That was only included in order to make the output of this library match that of the `bits` command, which in your linked issue appears to have been, itself, reversed. Okay, cool. So can you confirm that we should go ahead with the change?

https://github.com/faustomorales/pdqhash-python/blob/3c35e8dd2842c98055231aad2c60d835d0628b68/tests/test_compute.py#L9-L14

**Comment by BarrettOlson** [comment]
Yes, Brandon Bodnar @bodnarbm went ahead and fixed this confusing output on our end with https://github.com/facebook/ThreatExchange/pull/320

I agree we should go ahead with this change. I do have some concerns that someone using this library will encounter issues but luckily it is an easy enough operation to correct previously generated hashes (and doesn't required the original image).

Thank you for the quick follow up!

**Comment by faustomorales** [comment]
Cool, done. I've added a warning that will come up whenever someone installs the library indicating the change in vector format. Some time in the future I'll publish a new version with the warning removed.
